services:
  docker-updater:
    build: .
    container_name: docker-updater
    restart: unless-stopped
    ports:
      - "9292:9090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker:/volume1/docker:ro
      - ./data:/app/data
      - ./app.py:/app/app.py:ro
      - ./templates:/app/templates:ro
    environment:
      - CHECK_TIME=03:00
      - TIMEZONE=Australia/Melbourne
      - NOTIFY_URL=ntfy://ntfy.sh/liquidguru-docker
      - DOCKER_HOST=unix:///var/run/docker.sock
